# Generated by Django 3.0.3 on 2020-02-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndexPage', '0002_auto_20200206_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
